#!/bin/bash
# embed_roms.sh — Convert Adventure Vision ROMs into a C header
# Usage: ./embed_roms.sh <bios.rom> <game1.bin> [game2.bin] ...
#
# Output: embedded_roms.h (include in adventure_vision.c with -DEMBED_ROMS)

set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 <bios.rom> <game1.bin> [game2.bin] ..."
    echo ""
    echo "  First argument must be the BIOS ROM (1KB)"
    echo "  Remaining arguments are game ROMs (2-4KB each)"
    echo ""
    echo "Example:"
    echo "  $0 b225__ins8048-11kdp_n.u5 defender.bin supercobra.bin spaceforce.bin"
    exit 1
fi

OUT="embedded_roms.h"
BIOS="$1"
shift

if [ ! -f "$BIOS" ]; then
    echo "Error: BIOS file '$BIOS' not found"
    exit 1
fi

echo "/* Auto-generated by embed_roms.sh — do not edit */" > "$OUT"
echo "#ifndef EMBEDDED_ROMS_H" >> "$OUT"
echo "#define EMBEDDED_ROMS_H" >> "$OUT"
echo "" >> "$OUT"
echo "#include <stdint.h>" >> "$OUT"
echo "" >> "$OUT"

# Embed BIOS
echo "/* BIOS: $BIOS */" >> "$OUT"
echo "static const uint8_t embedded_bios[] = {" >> "$OUT"
xxd -i < "$BIOS" >> "$OUT"
echo "};" >> "$OUT"
echo "" >> "$OUT"

# Embed each game
GAME_COUNT=0
for ROM in "$@"; do
    if [ ! -f "$ROM" ]; then
        echo "Warning: '$ROM' not found, skipping"
        continue
    fi
    # Extract clean name from filename
    BASENAME=$(basename "$ROM")
    VARNAME=$(echo "$BASENAME" | sed 's/[^a-zA-Z0-9]/_/g' | sed 's/__*/_/g')
    DISPLAY=$(echo "$BASENAME" | sed 's/\.[^.]*$//' | sed 's/_/ /g' | sed 's/-/ /g')
    # Capitalize first letter
    DISPLAY="$(echo "${DISPLAY:0:1}" | tr '[:lower:]' '[:upper:]')${DISPLAY:1}"

    echo "/* Game $GAME_COUNT: $BASENAME */" >> "$OUT"
    echo "static const uint8_t embedded_game_${GAME_COUNT}[] = {" >> "$OUT"
    xxd -i < "$ROM" >> "$OUT"
    echo "};" >> "$OUT"
    echo "" >> "$OUT"

    GAME_NAMES[$GAME_COUNT]="$DISPLAY"
    GAME_SIZES[$GAME_COUNT]=$(wc -c < "$ROM")
    GAME_COUNT=$((GAME_COUNT + 1))
done

if [ $GAME_COUNT -eq 0 ]; then
    echo "Error: no valid game ROMs found"
    rm -f "$OUT"
    exit 1
fi

# Generate index structure
echo "typedef struct { const char *name; const uint8_t *data; int size; } EmbeddedRom;" >> "$OUT"
echo "" >> "$OUT"
echo "static const EmbeddedRom embedded_games[] = {" >> "$OUT"
for ((i=0; i<GAME_COUNT; i++)); do
    echo "    { \"${GAME_NAMES[$i]}\", embedded_game_${i}, ${GAME_SIZES[$i]} }," >> "$OUT"
done
echo "};" >> "$OUT"
echo "#define EMBEDDED_GAME_COUNT $GAME_COUNT" >> "$OUT"
echo "" >> "$OUT"
echo "#endif /* EMBEDDED_ROMS_H */" >> "$OUT"

echo "Generated $OUT with BIOS + $GAME_COUNT game(s)"
echo ""
echo "Build with:"
echo "  gcc -O2 -DUSE_SDL -DEMBED_ROMS -o advision adventure_vision.c -lSDL2 -lm"
